account:
  greeting: "안녕하세요"

---

spring:
  profiles: stg

account:
  greeting: "스테이징 서버에 오신걸 환영합니다."

---

spring:
  profiles: dev
  
account:
  greeting: "개발 서버에 오신걸 환영합니다!!!!"

---

spring:
  profiles: local
  
account:
  greeting: "로컬 서버에 오신걸 환영합니다."
