product:
  greeting: "운영 서버 상품서비스 입니다."

---

spring:
  profiles: stg

product:
  greeting: "스테이징 서버 상품서비스 입니다."

---

spring:
  profiles: dev

product:
  greeting: "개발 서버 상품서비스 입니다."

---

spring:
  profiles: local

product:
  greeting: "로컬 서버 상품서비스 입니다."
